services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: ["--db", "/data"]
    volumes:
      - ganache-db:/data
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8545"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  blockchain:
    build: ./blockchain
    depends_on:
      ganache:
        condition: service_healthy
    volumes:
      - ./:/repo
      - blockchain-data:/app/blockchain/build
    environment:
      - GANACHE_HOST=ganache
      - GANACHE_PORT=8545
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "test", "-f", "/app/blockchain/build/addresses.json"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  backend:
    build: ./backend
    depends_on:
      blockchain:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/repo
      - blockchain-data:/blockchain-build
    environment:
      - NODE_ENV=development
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./:/repo
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - africox-net

networks:
  africox-net:
    driver: bridge

volumes:
  blockchain-data:
  ganache-db:
