services:
  blockchain:
    build: ./blockchain
    volumes:
      - ./:/repo
      - blockchain-data:/app/blockchain/build
    environment:
      - GANACHE_HOST=localhost
      - GANACHE_PORT=8545
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "test", "-f", "/app/blockchain/build/addresses.json"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 60s  # Increased to allow more time for startup

  backend:
    build: ./backend
    depends_on:
      blockchain:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/repo
      - blockchain-data:/blockchain-build
    environment:
      - NODE_ENV=development
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./:/repo
    environment:
      - VITE_API_URL=http://localhost:3000  # Changed to localhost for browser access
    networks:
      - africox-net

networks:
  africox-net:
    driver: bridge

volumes:
  blockchain-data:
  ganache-db:
