services:
  blockchain:
    build: ./blockchain
    restart: unless-stopped
    volumes:
      - ./:/repo
      - blockchain-data:/app/blockchain/build
    ports:
      - "8545:8545"  # Expose Ganache port
    environment:
      - GANACHE_HOST=0.0.0.0
      - GANACHE_PORT=8545
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "test", "-f", "/app/blockchain/build/addresses.json"]
      interval: 150s
      timeout: 5s
      retries: 10
      start_period: 60s  # Increased to allow more time for startup

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      blockchain:
        condition: service_healthy
    ports:
      - "3000"
    volumes:
      - ./:/repo
      - blockchain-data:/app/blockchain/build
    environment:
      - NODE_ENV=development
    networks:
      - africox-net
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "3000"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173"
    volumes:
      - ./:/repo
    environment:
      - VITE_API_URL=http://localhost:3000  # Changed to localhost for browser access
    networks:
      - africox-net
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - africox-net

networks:
  africox-net:
    driver: bridge

volumes:
  blockchain-data:
  ganache-db:
