services:
  clone:
    image: bitnami/git:latest
    command: ["/bin/sh", "-c", "if [ ! -d /repo/.git ]; then git clone $GIT_REPO_URL /repo; else echo 'Repo already cloned'; fi"]
    environment:
      - GIT_REPO_URL=https://github.com/chyna-gvng/africo-x.git
    volumes:
      - repo-data:/repo
    networks:
      - africox-net

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: ["--db", "/data"]
    volumes:
      - ganache-db:/data
    networks:
      - africox-net

  blockchain:
    build: ./blockchain
    depends_on:
      - clone
      - ganache
    volumes:
      - repo-data:/repo
      - blockchain-data:/app/blockchain/build
    environment:
      - GANACHE_HOST=ganache
      - GANACHE_PORT=8545
    networks:
      - africox-net

  backend:
    build: ./backend
    depends_on:
      - blockchain
    ports:
      - "3000:3000"
    volumes:
      - repo-data:/repo
      - blockchain-data:/blockchain-build
    environment:
      - NODE_ENV=development
    networks:
      - africox-net

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - repo-data:/repo
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - africox-net

networks:
  africox-net:
    driver: bridge

volumes:
  repo-data:
  blockchain-data:
  ganache-db:
